import { useEffect, useState } from "react";
import { Label } from "../../ui/label";
import { RadioGroup, RadioGroupItem } from "../../ui/radio-group";
import { CheckboxField } from "../form/checkbox-field";
import { SegmentedField } from "../form/segmented-field";
import { FormSection, RecordDialog } from "../layout/RecordDialog";

export type DocumentSuggestionScope = "company" | "book" | "documentType";
export type DocumentAmountFromLines = "book" | "always" | "never";
export type DocumentAccountDisplay = "number" | "numberName";
export interface DocumentSettingsValue { suggestDescription: boolean; descriptionScope: DocumentSuggestionScope; suggestCounterparty: boolean; counterpartyScope: DocumentSuggestionScope; amountFromLines: DocumentAmountFromLines; showQuantityColumns: boolean; accountDisplay: DocumentAccountDisplay; offerPrintAfterSave: boolean; printTwoPerPage: boolean; printDocumentNumber: boolean; copies: number; /** Zadávat částky bez DPH / s DPH (jen při `showVatCalcMode`). */ vatCalcMode?: "net" | "gross"; }
export interface DocumentSettingsDialogTexts { title: string; entrySection: string; printSection: string; suggestDescription: string; suggestCounterparty: string; companyScope: string; bookScope: string; documentTypeScope: string; amountFromLines: string; accordingToBook: string; alwaysOn: string; alwaysOff: string; showQuantityColumns: string; accountDisplay: string; accountDisplayNumber: string; accountDisplayNumberName: string; offerPrintAfterSave: string; printTwoPerPage: string; printDocumentNumber: string; copies: string; vatCalcMode: string; vatCalcNet: string; vatCalcGross: string; cancel: string; save: string; }
export const DEFAULT_DOCUMENT_SETTINGS_TEXTS: DocumentSettingsDialogTexts = {
  title: "Nastavení dokladu", entrySection: "Zadávání dokladu", printSection: "Tisk", suggestDescription: "Nabízet v poli Popis dříve zadané hodnoty", suggestCounterparty: "Nabízet v poli Přijato od / Vyplaceno komu dříve zadané hodnoty", companyScope: "V celé firmě", bookScope: "Jen v rámci knihy", documentTypeScope: "Jen v rámci druhu dokladu", amountFromLines: "Sčítat částku z rozpisu", accordingToBook: "Podle knihy", alwaysOn: "Vždy zapnout", alwaysOff: "Vždy vypnout", showQuantityColumns: "Zobrazovat sloupce Množství, MJ, Cena za MJ", accountDisplay: "Účet v gridu řádků", accountDisplayNumber: "Zkráceně – 501.100", accountDisplayNumberName: "Celý – 501.100 - Spotřeba materiálu", offerPrintAfterSave: "Po uložení nového dokladu nabídnout tisk", printTwoPerPage: "Tisknout 2 doklady na stránku", printDocumentNumber: "Tisknout číslo dokladu", copies: "Počet kopií", vatCalcMode: "Zadávat částky", vatCalcNet: "Bez DPH", vatCalcGross: "S DPH", cancel: "Zrušit", save: "Uložit",
};
export interface DocumentSettingsDialogProps { open: boolean; onOpenChange: (open: boolean) => void; value: DocumentSettingsValue; onSave: (value: DocumentSettingsValue) => void | Promise<void>; documentTypeLabel: string; allowCounterpartySuggestions?: boolean; /** Zobrazí volbu „Zadávat částky: Bez DPH / S DPH“. */ showVatCalcMode?: boolean; busy?: boolean; texts?: Partial<DocumentSettingsDialogTexts>; }
function RadioOptions({ name, value, onChange, options }: { name: string; value: string; onChange: (value: string) => void; options: { value: string; label: string }[] }) {
  return <RadioGroup value={value} onValueChange={onChange} className="gap-2 pl-6">{options.map((option) => { const id = `${name}-${option.value}`; return <div key={option.value} className="flex items-center gap-2"><RadioGroupItem id={id} value={option.value} /><Label htmlFor={id} className="font-normal">{option.label}</Label></div>; })}</RadioGroup>;
}
/** Nastavení zadávání a tisku druhu dokladu, ukládané společně tlačítkem Uložit. */
export function DocumentSettingsDialog({ open, onOpenChange, value, onSave, documentTypeLabel, allowCounterpartySuggestions = false, showVatCalcMode = false, busy, texts }: DocumentSettingsDialogProps) {
  const t = { ...DEFAULT_DOCUMENT_SETTINGS_TEXTS, ...texts }; const [draft, setDraft] = useState(value);
  useEffect(() => { if (open) setDraft(value); }, [open, value]);
  const patch = (next: Partial<DocumentSettingsValue>) => setDraft((current) => ({ ...current, ...next }));
  const scopes = [{ value: "company", label: t.companyScope }, { value: "book", label: t.bookScope }, { value: "documentType", label: t.documentTypeScope }];
  return <RecordDialog open={open} onOpenChange={onOpenChange} title={t.title} headerExtra={<span className="text-sm text-muted-foreground">{documentTypeLabel}</span>} busy={busy} submitLabel={t.save} cancelLabel={t.cancel} onSubmit={() => void onSave(draft)}>
    <FormSection title={t.entrySection}><CheckboxField checked={draft.suggestDescription} onCheckedChange={(suggestDescription) => patch({ suggestDescription })} label={t.suggestDescription} />{draft.suggestDescription ? <RadioOptions name="description-scope" value={draft.descriptionScope} onChange={(descriptionScope) => patch({ descriptionScope: descriptionScope as DocumentSuggestionScope })} options={scopes} /> : null}{allowCounterpartySuggestions ? <><CheckboxField checked={draft.suggestCounterparty} onCheckedChange={(suggestCounterparty) => patch({ suggestCounterparty })} label={t.suggestCounterparty} />{draft.suggestCounterparty ? <RadioOptions name="counterparty-scope" value={draft.counterpartyScope} onChange={(counterpartyScope) => patch({ counterpartyScope: counterpartyScope as DocumentSuggestionScope })} options={scopes} /> : null}</> : null}<div className="space-y-2"><p className="text-sm font-medium">{t.amountFromLines}</p><RadioOptions name="amount-from-lines" value={draft.amountFromLines} onChange={(amountFromLines) => patch({ amountFromLines: amountFromLines as DocumentAmountFromLines })} options={[{ value: "book", label: t.accordingToBook }, { value: "always", label: t.alwaysOn }, { value: "never", label: t.alwaysOff }]} /></div><div className="space-y-2"><p className="text-sm font-medium">{t.accountDisplay}</p><RadioOptions name="account-display" value={draft.accountDisplay} onChange={(accountDisplay) => patch({ accountDisplay: accountDisplay as DocumentAccountDisplay })} options={[{ value: "number", label: t.accountDisplayNumber }, { value: "numberName", label: t.accountDisplayNumberName }]} /></div>{showVatCalcMode ? <div className="space-y-2"><p className="text-sm font-medium">{t.vatCalcMode}</p><SegmentedField ariaLabel={t.vatCalcMode} value={draft.vatCalcMode ?? "net"} onChange={(vatCalcMode) => patch({ vatCalcMode })} options={[{ value: "net", label: t.vatCalcNet }, { value: "gross", label: t.vatCalcGross }]} /></div> : null}<CheckboxField checked={draft.showQuantityColumns} onCheckedChange={(showQuantityColumns) => patch({ showQuantityColumns })} label={t.showQuantityColumns} /></FormSection>
    <FormSection title={t.printSection}><CheckboxField checked={draft.offerPrintAfterSave} onCheckedChange={(offerPrintAfterSave) => patch({ offerPrintAfterSave })} label={t.offerPrintAfterSave} /><CheckboxField checked={draft.printTwoPerPage} onCheckedChange={(printTwoPerPage) => patch({ printTwoPerPage })} label={t.printTwoPerPage} /><CheckboxField checked={draft.printDocumentNumber} onCheckedChange={(printDocumentNumber) => patch({ printDocumentNumber })} label={t.printDocumentNumber} /><div className="space-y-1"><Label>{t.copies}</Label><RadioOptions name="copies" value={String(draft.copies)} onChange={(copies) => patch({ copies: Number(copies) })} options={[1, 2, 3, 4, 5].map((copies) => ({ value: String(copies), label: String(copies) }))} /></div></FormSection>
  </RecordDialog>;
}