/** Texty formuláře dokladu; vlastní překlad, nesmí obsahovat React ani chování. */
import type { DsTexts } from "./types";

/** Úplné texty formuláře dokladu v daném jazyce. */
export const DOCUMENT_FORM_TEXTS_CS: DsTexts["documentForm"] = {
  changeAccount: "Změnit účet",
  currencyDisabled: "Měnu nelze změnit",
  mainAccountSelect: "Hlavní účet",
  supplierNumber: "Číslo dokladu dodavatele",
  supplierTaxDocumentNumber: "Číslo daňového dokladu",
  documentNumberTooLongForVs: "Číslo má víc než 10 číslic – VS doplňte ručně",
  bankAccountInvalid: "Číslo účtu není platné.",
  bankCodeInvalid: "Kód banky není platný.",
  otherBankAccount: "Jiný účet",
  editSelected: "Upravit vybraný záznam",
  manualAccountNumber: "Číslo účtu",
  accountNumberPattern: "předčíslí-číslo",
  manualAccountWithoutIban: "Číslo účtu bez IBAN",
  invalidIban: "IBAN není platný",
  invalidSwift: "SWIFT/BIC musí mít 8 nebo 11 znaků",
  swiftRequired: "Doplňte SWIFT/BIC",
  addBankAccount: "Přidat účet…",
  selectSupplierFirst: "Nejdřív vyberte dodavatele",
  invalidBankAccountWarning: "Bankovní účet je označen jako neplatný",
  invalidBankAccount: "neplatný",
  bankAccountMissing: "Účet není v číselníku partnera",
  paymentMethod: "Způsob platby",
  companyBankAccount: "Bankovní účet firmy",
  vatVerified: (date) => `Ověřeno ${date}`,
  counterpartyTab: "Odběratel",
  printTab: "Tiskové údaje",
  reloadFromPartner: "Načíst znovu z partnera",
  name: "Název",
  ico: "IČO",
  dic: "DIČ",
  email: "E-mail",
  phone: "Telefon",
  printGeneral: "Obecné",
  printItems: "Položky",
  issuedBy: "Vystavil",
  printHeader: "Tisknout záhlaví",
  printFooter: "Tisknout zápatí",
  printVatRecap: "Tisknout rekapitulaci DPH",
  printNote: "Tisknout poznámku",
  printColumnHeadings: "Tisknout nadpisy sloupců",
  printTotalsRow: "Tisknout součtový řádek",
  printPaymentSchedule: "Tisknout platební kalendář",
  headerText: "Záhlaví",
  footerText: "Zápatí",
  note: "Poznámka",
  selectFromDirectory: "Vybrat z adresáře",
  enterManually: "Zadat ručně",
  replaceManualCounterparty: "Ručně zadané údaje budou nahrazeny údaji partnera",
  counterpartyLocked: "Režim protistrany nelze změnit",
  manuallyEdited: "upraveno ručně",
  refreshCounterparty: "Aktualizovat z partnera",
  frozenAt: (date) => `Údaje zmrazeny při zařazení ${date}`,
  payByOrder: "Platit příkazem",
  excludeFromPaymentOrders: "Nezahrnovat do platebních příkazů",
  paymentOrderDisabled: "Doklad se nezahrnuje do platebních příkazů",
  payToBankAccount: "Uhradit na bankovní účet",
  street: "Ulice",
  houseNumber: "Číslo",
  zip: "PSČ",
  city: "Město",
  country: "Země",
  refreshCounterpartyConfirm: "Údaje odběratele budou přepsány aktuálními údaji z karty partnera.",
  bankCodeRequired: "Doplňte kód banky (4 číslice)",
  accountRequired: "Doplňte číslo účtu nebo IBAN",
  accountOrIban: "Zadejte buď IBAN, nebo číslo účtu – ne obojí",
  vsColumn: "VS",
  clear: "Vymazat",
};
