/**
 * České texty design systému (výchozí jazyk knihovny).
 * Vlastní: hodnoty DS_TEXTS_CS.
 * Nesmí: obsahovat React kód ani slovenské texty.
 */
import { cs } from "date-fns/locale";

import type { DsTexts } from "./types";

/** Výchozí české texty všech komponent. */
export const DS_TEXTS_CS: DsTexts = {
  locale: "cs",
  intlLocale: "cs-CZ",
  dateLocale: cs,
  paneChrome: {
    back: "Zpět (Alt+←)",
    forward: "Vpřed (Alt+→)",
    history: "Historie záložky",
    openInNewTab: "Otevřít v nové záložce",
    unsaved: "Neuložené změny",
    prevRecord: "Předchozí záznam (Alt+↑)",
    nextRecord: "Další záznam (Alt+↓)",
    maximize: "Maximalizovat panel (Alt+M)",
    restore: "Obnovit rozložení (Esc)",
    more: "Další akce záložky",
    closeTab: "Zavřít záložku",
    closeOthers: "Zavřít ostatní",
    moveToPane: "Přesunout záložku do panelu {index}",
    duplicate: "Duplikovat záložku",
    reopenClosed: "Znovu otevřít zavřenou záložku",
    closePane: "Zavřít panel",
    pageActions: "Akce stránky",
    untitled: "Bez názvu",
  },
  layoutMenu: {
    trigger: "Rozložení",
    empty: "Zatím žádné uložené rozložení",
    saveCurrent: "Uložit aktuální jako nové…",
    overwrite: "Přepsat uložené aktuálním",
    manage: "Spravovat rozložení",
    saveTitle: "Uložit rozložení",
    nameLabel: "Název",
    save: "Uložit",
    cancel: "Zrušit",
    manageTitle: "Uložená rozložení",
    close: "Zavřít",
    delete: "Odstranit",
    deleteTitle: "Odstranit rozložení?",
    deleteDescription: "Rozložení „{name}“ bude odstraněno.",
    moveUp: "Posunout nahoru",
    moveDown: "Posunout dolů",
  },
  common: {
    close: "Zavřít",
    cancel: "Zrušit",
    confirm: "Potvrdit",
    understand: "Rozumím",
    save: "Uložit",
    yes: "ano",
    no: "ne",
    system: "Systém",
  },
  recordAction: {
    moreActions: "Další akce",
    unsaved: "Neuložené změny",
    errorTitle: "Záznam nelze uložit",
    closeError: "Zavřít chybovou hlášku",
  },
  grid: {
    locale: "cs-CZ",
    searchPlaceholder: "Hledat…",
    searchLabel: "Hledat",
    clearSearchLabel: "Zrušit hledání",
    refresh: "Obnovit data",
    columnsTitle: "Sloupce",
    selectMore: "Vybrat více",
    cancelSelection: "Zrušit výběr",
    selectedRecords: (c) => `Vybraných záznamů: ${c}`,
    selectAllRows: "Vybrat všechny řádky",
    selectRow: "Vybrat řádek",
    actions: "Akce",
    edit: "Upravit",
    remove: "Odstranit",
    removeConfirm: "Opravdu odstranit tento záznam?",
    cancel: "Zrušit",
    emptyTitle: "Zatím zde nejsou žádné záznamy",
    searchEmptyTitle: "Hledání neodpovídá žádný záznam",
    emptyValue: "(prázdné)",
    valuesCount: (c) => `${c} hodnot`,
    total: "Celkem",
    sidePanelLabel: "Poznámky k vybranému záznamu",
    filterLabel: (l) => `Filtrovat ${l}`,
    filterSearchPlaceholder: "Hledat…",
    selectAll: "Vybrat vše",
    clear: "Vymazat",
    noValues: "Žádné hodnoty.",
    dateFilterYears: "Roky",
    dateFilterQuarters: "Čtvrtletí",
    dateFilterMonths: "Měsíce",
    dateFilterDates: "Jednotlivá data",
    dateFilterQuarter: (q, y) => `${q}. čtvrtletí ${y}`,
    showFilters: "Zobrazit filtry",
    activeFilters: "Aktivní filtry",
    activeCount: (c) => `${c} aktivní`,
    defaultFilters: "Výchozí filtry",
    clearAllFilters: "Zrušit všechny filtry",
    clearFilter: "Zrušit filtr",
    removeFilter: (l) => `Zrušit filtr ${l}`,
    clearAll: "Zrušit vše",
    rowsLabel: "řádků",
    show: "Zobrazit",
    all: "Vše",
    pageSize: "Počet záznamů na stránku",
    noRecords: "žádné záznamy",
    page: (p, n) => `Strana ${p} / ${n}`,
    previousPage: "Předchozí stránka",
    nextPage: "Další stránka",
    download: "Stáhnout",
    downloadExcel: "Stáhnout do Excelu",
    downloadPdf: "Stáhnout do PDF",
    downloadHtml: "Stáhnout do HTML",
    retry: "Zkusit znovu",
    loading: "Načítám data…",
    groupingEnable: "Seskupit podle sloupce",
    groupingDisable: "Vypnout seskupení",
    groupingDropHint: "Přetáhněte sem záhlaví sloupce pro seskupení",
    groupingAddColumn: "+ Přidat sloupec",
    groupingClear: "Zrušit seskupení",
    groupingEmpty: "(nevyplněno)",
    groupingHidden: (c) => `Skrytý pruh se seskupením (${c}) – zobrazit`,
    groupedCount: (c) => `Seskupeno (${c})`,
    groupingMoveLeft: "Posunout doleva",
    groupingMoveRight: "Posunout doprava",
    groupingDateBy: "Seskupit datum podle",
    groupingRemoveColumn: "Zrušit seskupení podle sloupce",
    groupDay: "Den",
    groupMonth: "Měsíc",
    groupQuarter: "Čtvrtletí",
    groupYear: "Rok",
    quarterLabel: (q, y) => `${q}. čtvrtletí ${y}`,
    zoomOut: "Zmenšit tabulku",
    zoomIn: "Zvětšit tabulku",
    zoomReset: "Výchozí velikost",
    normalDensity: "Normální hustota řádků",
    compactDensity: "Kompaktní hustota řádků",
    resizeColumn: "Změnit šířku sloupce",
    resizeColumnHint: "Tažením změníte šířku, dvojklik vrátí automatickou šířku",
    moreActions: "Další akce",
    moreParameters: "Parametry",
    moreTools: "Nástroje",
    treeView: "Stromové zobrazení",
    tableView: "Tabulkové zobrazení",
    groupTotal: (l) => `Celkem ${l}`,
    sortBy: (l) => `Seřadit podle ${l}`,
    expand: "Rozbalit",
    collapse: "Sbalit",
    expandLevel: (n, l) => `Úroveň ${n} – ${l}`,
    exportSearch: (q) => `Hledání: ${q}`,
    recordsCount: (c) => `${c} záznamů`,
  },
  appShell: {
    clearSearch: "Smazat hledání",
    mainMenu: "Hlavní menu",
    containsActivePage: "Obsahuje aktivní stránku",
    disabledHint: "Připravujeme",
    searchPlaceholder: "Hledat v menu…",
    searchEmpty: "Nic nenalezeno",
    resizeMenu: "Změnit šířku menu",
    panelView: "Část panelu",
    contextDisabledHint: "Firma a období se tady neuplatní – nastavení platí pro celý prostor",
  },
  panes: {
    panel: (i) => `Panel ${i}`,
    emptyHint: "Otevřete položku z menu",
    maximizedBanner: "Panel {index} je maximalizovaný",
    restoreLayout: "Obnovit rozložení",
    limitClosed:
      "Zavřené záložky: {count} – v panelu může být nejvýše {max}. Alt+Shift+T je vrátí.",
  },
  notification: {
    label: "Oznámení",
    title: "Oznámení",
    markAllRead: "Označit vše jako přečtené",
    empty: "Žádná oznámení",
    showAll: "Zobrazit vše",
    loading: "Načítání oznámení",
  },
  standalone: { close: "Zavřít", pages: "Stránky", pagesSelect: "Vyberte stránku" },
  contextSwitcher: {
    search: "Hledat…",
    empty: "Nic nenalezeno",
    current: "Aktuální",
    selected: "Vybráno",
  },
  confirmByTyping: { instruction: "Pro potvrzení opište:", cancel: "Zrušit", running: "Probíhá…" },
  dangerZone: { title: "Nebezpečná zóna" },
  noticeBar: { close: "Zavřít upozornění" },
  maskInput: {
    preview: "Náhled příštího čísla",
    tokens: [
      { token: "{KOD}", label: "Kód číselné řady" },
      { token: "{SMER}", label: "Směr dokladu" },
      { token: "{OBD}", label: "Účetní období" },
      { token: "{RRRR}", label: "Rok čtyřmi číslicemi" },
      { token: "{RR}", label: "Rok dvěma číslicemi" },
      { token: "{MM}", label: "Měsíc" },
      { token: "{Q}", label: "Čtvrtletí" },
      { token: "{###}", label: "Pořadové číslo" },
    ],
  },
  appZoom: {
    label: "Velikost zobrazení",
    decrease: "Zmenšit zobrazení",
    increase: "Zvětšit zobrazení",
    reset: "Obnovit",
  },
  recordDialog: {
    detailSections: "Sekce detailu",
    hidePanel: (p) => `Skrýt ${p}`,
    notes: "Poznámky",
    active: "Aktivní",
    inactive: "Neaktivní",
    saveAndAction: "Uložit změny a {label}",
    dirtyTitle: "Formulář obsahuje neuložené změny",
    history: "Historie změn",
    noHistory: "Zatím bez zaznamenaných změn.",
    system: "Systém",
    yes: "ano",
    no: "ne",
  },
  date: {
    chooseDate: "Vyberte datum",
    dateSelection: "Výběr data",
    openCalendar: "Otevřít kalendář",
    invalidFormat: (f) => `Zadejte platné datum ve formátu ${f}.`,
    sameAsIssue: "Stejné jako datum vystavení – klikněte pro úpravu",
    relinkIssue: "Znovu svázat s datem vystavení",
    rangePlaceholder: "Vyberte období",
    rangeLabel: "Rozsah dat",
    clear: "Vymazat",
    chooseRangeEnd: "Vyberte konec rozsahu",
    openTime: "Otevřít výběr času",
    all: "Vše",
    day: "Den",
    week: "Týden",
    month: "Měsíc",
    year: "Rok",
    custom: "Vlastní",
    from: "Od",
    to: "Do",
  },
  country: {
    choose: "Vyberte stát",
    search: "Hledat stát nebo kód…",
    emptyTitle: "Nic jsme nenašli",
    emptyDescription: (q) =>
      `Pro „${q}“ neodpovídá žádný stát. Zkuste jiný název nebo ISO kód (např. CR).`,
    recent: "Nedávno použité",
    eu: "Evropská unie",
    other: "Ostatní státy",
  },
  multiSelect: { selectAll: "Vybrat vše", noValues: "Žádné hodnoty." },
  optionSelect: {
    emptyValue: "— nevybráno —",
    inactive: "neaktivní",
    unknownValue: "Hodnota není v číselníku",
    searchPlaceholder: "Hledat…",
    noResults: "Žádná hodnota nenalezena",
  },
  tree: { expand: "Rozbalit", collapse: "Sbalit", breadcrumbs: "Drobečková navigace" },
  contacts: {
    blacklist: "Blacklist",
    companyId: "IČO:",
    personalId: "RČ:",
    openRegistry: "Otevřít v obchodním rejstříku",
    openAres: "Otevřít v ARES",
  },
  accessibility: { resizeCombobox: "Změnit šířku tažením" },
  company: { companyId: "IČO" },
  errors: {
    load: "Data se nepodařilo načíst.",
    network: "Spojení se serverem se nezdařilo.",
    networkDetail: "Zkontrolujte připojení k internetu a zkuste to znovu.",
    expired: "Přihlášení vypršelo.",
    expiredDetail: "Přihlaste se prosím znovu a akci zopakujte.",
    forbidden: "K těmto datům nemáte oprávnění.",
    forbiddenDetail: "Požádejte správce účtu o přidělení role.",
    timeout: "Načítání trvalo příliš dlouho.",
    timeoutDetail: "Zkuste zúžit období nebo akci opakovat.",
  },
  columnPicker: {
    clearCustom: "Zrušit vlastní",
    clearCustomTitle: "Zruší uložené vlastní výchozí nastavení sloupců",
    default: "Výchozí",
    restoreSaved: "Obnovit uložené výchozí nastavení",
    restoreFactory: "Obnovit tovární výchozí nastavení",
    showSection: (s) => `Zobrazit sekci ${s}`,
    hideSection: (s) => `Skrýt sekci ${s}`,
    show: "Zobrazit",
    hide: "Skrýt",
    saveDefault: "Uložit aktuální viditelnost i pořadí sloupců jako výchozí",
    saved: "Uloženo",
    saveColumns: "Uložit nastavení sloupců",
    persistenceHint: "Pořadí i viditelnost se ukládají jako výchozí zobrazení.",
    savedViews: "Uložené pohledy",
    noSavedViews: "Zatím nemáte uložený žádný pohled.",
    applyView: "Použít pohled",
    overwrite: "Přepsat",
    overwriteTitle: "Přepsat aktuálním nastavením",
    deleteView: "Smazat pohled",
    viewName: "Název pohledu",
    saveView: "Uložit aktuální zobrazení",
    save: "Uložit",
    accountFormRequired: "Aspoň jedna forma účtu musí zůstat zobrazená",
    compactAccountHeading: (l) => `${l} – zkráceno kvůli šířce`,
  },
  journalEditor: {
    row: "Ř.",
    debitAccount: "MD účet",
    creditAccount: "DAL účet",
    counterAccount: "Protiúčet",
    amount: "Částka",
    homeAmount: "Částka v {symbol}",
    foreignAmount: "Částka v {symbol}",
    text: "Text",
    quantity: "Množství",
    unit: "MJ",
    unitPrice: "Cena za MJ",
    dimension: "Zakázka",
    vs: "VS",
    partner: "Partner",
    debitDimension: "MD zakázka",
    creditDimension: "DAL zakázka",
    debitVs: "MD VS",
    creditVs: "DAL VS",
    debitPartner: "MD partner",
    creditPartner: "DAL partner",
    nonTax: "Nedaňový",
    nonTaxOn: "Nedaňový",
    nonTaxOff: "Daňový – klikněte pro nedaňový",
    rounding: "Zaokrouhlení",
    fxRounding: "Kurzové zaokrouhlení",
    fxRoundingPreview: "Kurzové zaokrouhlení – dopočítá se při uložení",
    fxRoundingHint: "Rozdíl mezi přepočtem celého dokladu a řádků – vytváří databáze",
    detail: "Detail řádku",
    showDetail: "Zobrazit detail řádku (Alt+↓)",
    hideDetail: "Skrýt detail řádku (Alt+↓)",
    sideDebit: "MD",
    sideCredit: "DAL",
    actions: "Akce",
    addLine: "Přidat řádek",
    duplicateLine: "Duplikovat řádek",
    removeLine: "Odebrat řádek",
    undo: "Zpět",
    removed: "Řádek byl odebrán",
    total: "Celkem",
    remaining: "Zbývá rozepsat",
    balanced: "Rozepsáno",
    roundingExists: "Zaokrouhlení už na dokladu je",
    errors: "Počet chyb",
    empty: "Zatím zde nejsou žádné řádky",
    debitRequired: "Vyberte účet MD",
    creditRequired: "Vyberte účet DAL",
    amountRequired: "Částka musí být nenulová",
    missingVs: "Chybí VS na straně {side}",
    missingDimension: "Chybí zakázka na straně {side}",
    search: "Hledat v řádcích…",
    searchResult: "Zobrazeno {shown} z {total} řádků",
    clearSearch: "Zrušit hledání",
    quantityPriceHint: "Množství × cena za MJ",
    vatCode: "Kód DPH",
    vatRate: "Sazba",
    vatAmount: "DPH",
    grossAmount: "Celkem s DPH",
    vatMode: "Zadání částky",
    vatModeNet: "Bez DPH",
    vatModeGross: "S DPH",
    vatManual: "Daň zadaná ručně",
    resetVat: "Vrátit vypočtenou daň",
    vatDeduction: "Nárok na odpočet",
    deductionFull: "Plný",
    deductionNone: "Bez nároku",
    deductionPartial: "Poměrný",
    deductionShare: "Poměr %",
    pdpSubject: "Předmět plnění PDP",
    vatBaseHome: "Základ pro DPH ({symbol})",
    vatHome: "DPH ({symbol})",
    vatCodeRequired: "Vyberte kód DPH",
    vatDeviation: "Ruční daň se liší od vypočtené o {amount}",
    pdpRequired: "Vyberte předmět plnění PDP",
    deductionShareRange: "Poměrný nárok musí být 1–99 %",
    vatMissingAccounts: "Chybí účty kódu {code} – daň se nezaúčtuje",
    rate: "Kurz",
    moveRow: "Přesunout řádek",
    nonTaxShort: "ND",
  },
  journalRecap: {
    debitShort: "MD",
    creditShort: "DAL",
    debitAccount: "MD účet",
    creditAccount: "DAL účet",
  },
  documentForm: {
    changeAccount: "Změnit účet",
    currencyDisabled: "Měnu nelze změnit",
    mainAccountSelect: "Hlavní účet",
    supplierNumber: "Číslo dokladu dodavatele",
    supplierTaxDocumentNumber: "Číslo daňového dokladu",
    documentNumberTooLongForVs: "Číslo má víc než 10 číslic – VS doplňte ručně",
    bankAccountInvalid: "Číslo účtu není platné.",
    bankCodeInvalid: "Kód banky není platný.",
    otherBankAccount: "Jiný účet",
    editSelected: "Upravit vybraný záznam",
    addBankAccount: "Přidat účet…",
    selectSupplierFirst: "Nejdřív vyberte dodavatele",
    invalidBankAccountWarning: "Bankovní účet je označen jako neplatný",
    invalidBankAccount: "neplatný",
    bankAccountMissing: "Účet není v číselníku partnera",
    paymentMethod: "Způsob platby",
    companyBankAccount: "Bankovní účet firmy",
    vatVerified: (date) => `Ověřeno ${date}`,
    counterpartyTab: "Odběratel",
    printTab: "Tiskové údaje",
    reloadFromPartner: "Načíst znovu z partnera",
    name: "Název",
    ico: "IČO",
    dic: "DIČ",
    email: "E-mail",
    phone: "Telefon",
    printGeneral: "Obecné",
    printItems: "Položky",
    issuedBy: "Vystavil",
    printHeader: "Tisknout záhlaví",
    printFooter: "Tisknout zápatí",
    printVatRecap: "Tisknout rekapitulaci DPH",
    printNote: "Tisknout poznámku",
    printColumnHeadings: "Tisknout nadpisy sloupců",
    printTotalsRow: "Tisknout součtový řádek",
    printPaymentSchedule: "Tisknout platební kalendář",
    headerText: "Záhlaví",
    footerText: "Zápatí",
    note: "Poznámka",
    selectFromDirectory: "Vybrat z adresáře",
    enterManually: "Zadat ručně",
    replaceManualCounterparty: "Ručně zadané údaje budou nahrazeny údaji partnera",
    counterpartyLocked: "Režim protistrany nelze změnit",
    manuallyEdited: "upraveno ručně",
    refreshCounterparty: "Aktualizovat z partnera",
    frozenAt: (date) => `Údaje zmrazeny při zařazení ${date}`,
    payByOrder: "Platit příkazem",
    excludeFromPaymentOrders: "Nezahrnovat do platebních příkazů",
    paymentOrderDisabled: "Doklad se nezahrnuje do platebních příkazů",
    payToBankAccount: "Uhradit na bankovní účet",
  },
  export: {
    parametersSheet: "Parametry exportu",
    parameter: "Parametr",
    value: "Hodnota",
    reportName: "Název sestavy",
    company: "Firma",
    period: "Období",
    exportedAt: "Exportováno",
    user: "Uživatel",
    activeFilters: "Aktivní filtry",
    pageFooter: "Strana &P z &N",
    fallbackColumn: (i) => `Sloupec ${i}`,
    printPdf: "Tisk (PDF)…",
  },
  print: {
    book: "Kniha",
    allBooks: "Všechny knihy",
    period: "Období",
    search: "Hledání",
    filter: "Filtr",
    asOf: "Stav k datu",
    total: "Celkem",
    portrait: "Na výšku",
    landscape: "Na šířku",
    orientation: "Orientace stránky",
    largeTitle: "Tisk velkého objemu dat",
    largeDescription: (r, p) =>
      `Sestava má ${r} řádků, odhadem ${p} stran. Příprava PDF může chvíli trvat. Pokračovat?`,
    print: "Vytisknout",
    printTitle: "Tisk",
    downloadPdf: "Stáhnout PDF",
    preview: "Náhled",
    preparing: "Připravuji náhled…",
    printedBy: "Vytiskl:",
    page: (p, n) => `Strana ${p} z ${n}`,
  },
};
