/** Typy textů gridů a editoru řádků; bez hodnot a chování. */
export interface GridTexts {
  locale: string;
  searchPlaceholder: string;
  searchLabel: string;
  clearSearchLabel: string;
  refresh: string;
  columnsTitle: string;
  selectMore: string;
  cancelSelection: string;
  selectedRecords: (count: string) => string;
  selectAllRows: string;
  selectRow: string;
  actions: string;
  edit: string;
  remove: string;
  removeConfirm: string;
  cancel: string;
  emptyTitle: string;
  searchEmptyTitle: string;
  emptyValue: string;
  valuesCount: (count: number) => string;
  total: string;
  sidePanelLabel: string;
  filterLabel: (label: string) => string;
  filterSearchPlaceholder: string;
  selectAll: string;
  clear: string;
  noValues: string;
  dateFilterYears: string;
  dateFilterQuarters: string;
  dateFilterMonths: string;
  dateFilterDates: string;
  dateFilterQuarter: (quarter: number, year: number) => string;
  showFilters: string;
  activeFilters: string;
  activeCount: (count: number) => string;
  defaultFilters: string;
  clearAllFilters: string;
  clearFilter: string;
  removeFilter: (label: string) => string;
  clearAll: string;
  rowsLabel: string;
  show: string;
  all: string;
  pageSize: string;
  noRecords: string;
  page: (page: number, pageCount: number) => string;
  previousPage: string;
  nextPage: string;
  download: string;
  downloadExcel: string;
  downloadPdf: string;
  downloadHtml: string;
  retry: string;
  loading: string;
  groupingEnable: string;
  groupingDisable: string;
  groupingDropHint: string;
  groupingAddColumn: string;
  groupingClear: string;
  groupingEmpty: string;
  groupingHidden: (count: number) => string;
  groupedCount: (count: number) => string;
  groupingMoveLeft: string;
  groupingMoveRight: string;
  groupingDateBy: string;
  groupingRemoveColumn: string;
  groupDay: string;
  groupMonth: string;
  groupQuarter: string;
  groupYear: string;
  quarterLabel: (quarter: number, year: string | number) => string;
  zoomOut: string;
  zoomIn: string;
  zoomReset: string;
  normalDensity: string;
  compactDensity: string;
  resizeColumn: string;
  resizeColumnHint: string;
  moreActions: string;
  moreParameters: string;
  moreTools: string;
  treeView: string;
  tableView: string;
  groupTotal: (label: string) => string;
  sortBy: (label: string) => string;
  expand: string;
  collapse: string;
  expandLevel: (level: number, label: string) => string;
  exportSearch: (query: string) => string;
  recordsCount: (count: number) => string;
}

/** Texty editoru řádků dokladu; prop `texts` editoru je částečný přepis. */
export interface JournalEditorTexts {
  row: string;
  debitAccount: string;
  creditAccount: string;
  counterAccount: string;
  /** Přepíše sdílený text `DsTexts.columnPicker.accountFormRequired`. */
  accountFormRequired?: string;
  amount: string;
  homeAmount: string;
  foreignAmount: string;
  text: string;
  quantity: string;
  unit: string;
  unitPrice: string;
  dimension: string;
  vs: string;
  partner: string;
  debitDimension: string;
  creditDimension: string;
  debitVs: string;
  creditVs: string;
  debitPartner: string;
  creditPartner: string;
  nonTax: string;
  nonTaxOn: string;
  nonTaxOff: string;
  rounding: string;
  fxRounding: string;
  fxRoundingPreview: string;
  fxRoundingHint: string;
  detail: string;
  showDetail: string;
  hideDetail: string;
  sideDebit: string;
  sideCredit: string;
  actions: string;
  addLine: string;
  duplicateLine: string;
  removeLine: string;
  undo: string;
  removed: string;
  total: string;
  remaining: string;
  balanced: string;
  roundingExists: string;
  /** @deprecated Od 2.54; počet chyb předejte přes onValidationChange. Odstraní se ve 3.0.0. */
  errors: string;
  empty: string;
  debitRequired: string;
  creditRequired: string;
  amountRequired: string;
  missingVs: string;
  missingDimension: string;
  search: string;
  searchResult: string;
  clearSearch: string;
  quantityPriceHint: string;
  vatCode: string;
  vatRate: string;
  vatAmount: string;
  grossAmount: string;
  vatMode: string;
  vatModeNet: string;
  vatModeGross: string;
  vatManual: string;
  resetVat: string;
  vatDeduction: string;
  deductionFull: string;
  deductionNone: string;
  deductionPartial: string;
  deductionShare: string;
  pdpSubject: string;
  vatBaseHome: string;
  vatHome: string;
  vatCodeRequired: string;
  vatDeviation: string;
  pdpRequired: string;
  deductionShareRange: string;
  vatMissingAccounts: string;
  /** Popisek sloupce kurzu. */
  rate: string;
  /** Přístupný název úchytu pro přesun řádku. */
  moveRow: string;
  /** Zkratka nedaňového řádku na přepínači. */
  nonTaxShort: string;
}

