/**
 * Slovenské texty design systému.
 * Vlastní: hodnoty DS_TEXTS_SK (chybějící klíče doplní čeština).
 * Nesmí: obsahovat React kód.
 */
import { sk } from "date-fns/locale";

import { DS_TEXTS_CS } from "./cs";
import type { DsTexts } from "./types";

/** Slovenské texty; aplikace je zapne přes DsTextsProvider locale="sk". */
export const DS_TEXTS_SK: DsTexts = {
  ...DS_TEXTS_CS,
  layoutMenu: {
    trigger: "Rozloženie",
    empty: "Zatiaľ žiadne uložené rozloženie",
    saveCurrent: "Uložiť aktuálne ako nové…",
    overwrite: "Prepísať uložené aktuálnym",
    manage: "Spravovať rozloženia",
    saveTitle: "Uložiť rozloženie",
    nameLabel: "Názov",
    save: "Uložiť",
    cancel: "Zrušiť",
    manageTitle: "Uložené rozloženia",
    close: "Zavrieť",
    delete: "Odstrániť",
    deleteTitle: "Odstrániť rozloženie?",
    deleteDescription: "Rozloženie „{name}“ bude odstránené.",
    moveUp: "Posunúť nahor",
    moveDown: "Posunúť nadol",
  },
  paneChrome: {
    back: "Späť (Alt+←)",
    forward: "Dopredu (Alt+→)",
    history: "História karty",
    openInNewTab: "Otvoriť v novej karte",
    unsaved: "Neuložené zmeny",
    prevRecord: "Predchádzajúci záznam (Alt+↑)",
    nextRecord: "Ďalší záznam (Alt+↓)",
    maximize: "Maximalizovať panel (Alt+M)",
    restore: "Obnoviť rozloženie (Esc)",
    more: "Ďalšie akcie karty",
    closeTab: "Zavrieť kartu",
    closeOthers: "Zavrieť ostatné",
    moveToPane: "Presunúť kartu do panela {index}",
    duplicate: "Duplikovať kartu",
    reopenClosed: "Znova otvoriť zavretú kartu",
    closePane: "Zavrieť panel",
    pageActions: "Akcie stránky",
    untitled: "Bez názvu",
  },
  locale: "sk",
  intlLocale: "sk-SK",
  dateLocale: sk,
  common: {
    close: "Zavrieť",
    cancel: "Zrušiť",
    confirm: "Potvrdiť",
    understand: "Rozumiem",
    save: "Uložiť",
    yes: "áno",
    no: "nie",
    system: "Systém",
  },
  recordAction: {
    moreActions: "Ďalšie akcie",
    unsaved: "Neuložené zmeny",
    errorTitle: "Záznam nie je možné uložiť",
    closeError: "Zavrieť chybové hlásenie",
  },
  grid: {
    ...DS_TEXTS_CS.grid,
    locale: "sk-SK",
    searchPlaceholder: "Hľadať…",
    searchLabel: "Hľadať",
    clearSearchLabel: "Zrušiť hľadanie",
    refresh: "Obnoviť údaje",
    columnsTitle: "Stĺpce",
    selectMore: "Vybrať viac",
    cancelSelection: "Zrušiť výber",
    selectedRecords: (c) => `Vybraných záznamov: ${c}`,
    selectAllRows: "Vybrať všetky riadky",
    selectRow: "Vybrať riadok",
    actions: "Akcie",
    edit: "Upraviť",
    remove: "Odstrániť",
    removeConfirm: "Naozaj odstrániť tento záznam?",
    cancel: "Zrušiť",
    emptyTitle: "Zatiaľ tu nie sú žiadne záznamy",
    searchEmptyTitle: "Hľadaniu nezodpovedá žiadny záznam",
    emptyValue: "(prázdne)",
    valuesCount: (c) => `${c} hodnôt`,
    total: "Celkom",
    sidePanelLabel: "Poznámky k vybranému záznamu",
    filterLabel: (l) => `Filtrovať ${l}`,
    filterSearchPlaceholder: "Hľadať…",
    selectAll: "Vybrať všetko",
    clear: "Vymazať",
    noValues: "Žiadne hodnoty.",
    dateFilterYears: "Roky",
    dateFilterQuarters: "Štvrťroky",
    dateFilterMonths: "Mesiace",
    dateFilterDates: "Jednotlivé dátumy",
    dateFilterQuarter: (q, y) => `${q}. štvrťrok ${y}`,
    showFilters: "Zobraziť filtre",
    activeFilters: "Aktívne filtre",
    activeCount: (c) => `${c} aktívne`,
    defaultFilters: "Predvolené filtre",
    clearAllFilters: "Zrušiť všetky filtre",
    clearFilter: "Zrušiť filter",
    removeFilter: (l) => `Zrušiť filter ${l}`,
    clearAll: "Zrušiť všetko",
    rowsLabel: "riadkov",
    show: "Zobraziť",
    all: "Všetko",
    pageSize: "Počet záznamov na stránku",
    noRecords: "žiadne záznamy",
    page: (p, n) => `Strana ${p} / ${n}`,
    previousPage: "Predchádzajúca strana",
    nextPage: "Ďalšia strana",
    download: "Stiahnuť",
    downloadExcel: "Stiahnuť do Excelu",
    downloadPdf: "Stiahnuť do PDF",
    downloadHtml: "Stiahnuť do HTML",
    retry: "Skúsiť znova",
    loading: "Načítavam údaje…",
    groupingEnable: "Zoskupiť podľa stĺpca",
    groupingDisable: "Vypnúť zoskupenie",
    groupingDropHint: "Presuňte sem záhlavie stĺpca na zoskupenie",
    groupingAddColumn: "+ Pridať stĺpec",
    groupingClear: "Zrušiť zoskupenie",
    groupingEmpty: "(nevyplnené)",
    groupingHidden: (c) => `Skrytý pruh so zoskupením (${c}) – zobraziť`,
    groupedCount: (c) => `Zoskupené (${c})`,
    groupingMoveLeft: "Posunúť doľava",
    groupingMoveRight: "Posunúť doprava",
    groupingDateBy: "Zoskupiť dátum podľa",
    groupingRemoveColumn: "Zrušiť zoskupenie podľa stĺpca",
    groupDay: "Deň",
    groupMonth: "Mesiac",
    groupQuarter: "Štvrťrok",
    groupYear: "Rok",
    quarterLabel: (q, y) => `${q}. štvrťrok ${y}`,
    zoomOut: "Zmenšiť tabuľku",
    zoomIn: "Zväčšiť tabuľku",
    zoomReset: "Predvolená veľkosť",
    normalDensity: "Normálna hustota riadkov",
    compactDensity: "Kompaktná hustota riadkov",
    resizeColumn: "Zmeniť šírku stĺpca",
    resizeColumnHint: "Ťahaním zmeníte šírku, dvojklik obnoví automatickú šírku",
    moreActions: "Ďalšie akcie",
    moreParameters: "Parametre",
    moreTools: "Nástroje",
    treeView: "Stromové zobrazenie",
    tableView: "Tabuľkové zobrazenie",
    groupTotal: (l) => `Celkom ${l}`,
    sortBy: (l) => `Zoradiť podľa ${l}`,
    expand: "Rozbaliť",
    collapse: "Zbaliť",
    expandLevel: (n, l) => `Úroveň ${n} – ${l}`,
    exportSearch: (q) => `Hľadanie: ${q}`,
    recordsCount: (c) => `${c} záznamov`,
  },
  appShell: {
    clearSearch: "Vymazať hľadanie",
    mainMenu: "Hlavné menu",
    containsActivePage: "Obsahuje aktívnu stránku",
    disabledHint: "Pripravujeme",
    searchPlaceholder: "Hľadať v menu…",
    searchEmpty: "Nič sa nenašlo",
    resizeMenu: "Zmeniť šírku menu",
    panelView: "Časť panela",
    contextDisabledHint: "Firma a obdobie sa tu neuplatnia – nastavenie platí pre celý priestor",
  },
  panes: {
    panel: (i) => `Panel ${i}`,
    emptyHint: "Otvorte položku z menu",
    maximizedBanner: "Panel {index} je maximalizovaný",
    restoreLayout: "Obnoviť rozloženie",
    limitClosed: "Zavreté karty: {count} – v paneli môže byť najviac {max}. Alt+Shift+T ich vráti.",
  },
  notification: {
    label: "Oznámenia",
    title: "Oznámenia",
    markAllRead: "Označiť všetko ako prečítané",
    empty: "Žiadne oznámenia",
    showAll: "Zobraziť všetko",
    loading: "Načítavanie oznámení",
  },
  standalone: { close: "Zavrieť", pages: "Stránky", pagesSelect: "Vyberte stránku" },
  contextSwitcher: {
    search: "Hľadať…",
    empty: "Nič sa nenašlo",
    current: "Aktuálny",
    selected: "Vybrané",
  },
  confirmByTyping: { instruction: "Na potvrdenie opíšte:", cancel: "Zrušiť", running: "Prebieha…" },
  dangerZone: { title: "Nebezpečná zóna" },
  noticeBar: { close: "Zavrieť upozornenie" },
  appZoom: {
    label: "Veľkosť zobrazenia",
    decrease: "Zmenšiť zobrazenie",
    increase: "Zväčšiť zobrazenie",
    reset: "Obnoviť",
  },
  recordDialog: {
    detailSections: "Sekcie detailu",
    hidePanel: (p) => `Skryť ${p}`,
    notes: "Poznámky",
    active: "Aktívny",
    inactive: "Neaktívny",
    saveAndAction: "Uložiť zmeny a {label}",
    dirtyTitle: "Formulár obsahuje neuložené zmeny",
    history: "História zmien",
    noHistory: "Zatiaľ bez zaznamenaných zmien.",
    system: "Systém",
    yes: "áno",
    no: "nie",
  },
  date: {
    chooseDate: "Vyberte dátum",
    dateSelection: "Výber dátumu",
    openCalendar: "Otvoriť kalendár",
    invalidFormat: (f) => `Zadajte platný dátum vo formáte ${f}.`,
    sameAsIssue: "Rovnaké ako dátum vystavenia – kliknite na úpravu",
    relinkIssue: "Znova prepojiť s dátumom vystavenia",
    rangePlaceholder: "Vyberte obdobie",
    rangeLabel: "Rozsah dátumov",
    clear: "Vymazať",
    chooseRangeEnd: "Vyberte koniec rozsahu",
    openTime: "Otvoriť výber času",
    all: "Všetko",
    day: "Deň",
    week: "Týždeň",
    month: "Mesiac",
    year: "Rok",
    custom: "Vlastné",
    from: "Od",
    to: "Do",
  },
  country: {
    choose: "Vyberte štát",
    search: "Hľadať štát alebo kód…",
    emptyTitle: "Nič sme nenašli",
    emptyDescription: (q) =>
      `Pre „${q}“ nezodpovedá žiadny štát. Skúste iný názov alebo ISO kód (napr. CR).`,
    recent: "Nedávno použité",
    eu: "Európska únia",
    other: "Ostatné štáty",
  },
  multiSelect: { selectAll: "Vybrať všetko", noValues: "Žiadne hodnoty." },
  tree: { expand: "Rozbaliť", collapse: "Zbaliť", breadcrumbs: "Omrvinková navigácia" },
  contacts: {
    blacklist: "Blokovaný",
    companyId: "IČO:",
    personalId: "RČ:",
    openRegistry: "Otvoriť v obchodnom registri",
    openAres: "Otvoriť v ARES",
  },
  accessibility: { resizeCombobox: "Zmeniť šírku ťahaním" },
  company: { companyId: "IČO" },
  errors: {
    load: "Údaje sa nepodarilo načítať.",
    network: "Spojenie so serverom zlyhalo.",
    networkDetail: "Skontrolujte internetové pripojenie a skúste to znova.",
    expired: "Prihlásenie vypršalo.",
    expiredDetail: "Prihláste sa znova a akciu zopakujte.",
    forbidden: "K týmto údajom nemáte oprávnenie.",
    forbiddenDetail: "Požiadajte správcu účtu o pridelenie roly.",
    timeout: "Načítavanie trvalo príliš dlho.",
    timeoutDetail: "Skúste zúžiť obdobie alebo akciu zopakovať.",
  },
  columnPicker: {
    clearCustom: "Zrušiť vlastné",
    clearCustomTitle: "Zruší uložené vlastné predvolené nastavenie stĺpcov",
    default: "Predvolené",
    restoreSaved: "Obnoviť uložené predvolené nastavenie",
    restoreFactory: "Obnoviť továrenské predvolené nastavenie",
    showSection: (s) => `Zobraziť sekciu ${s}`,
    hideSection: (s) => `Skryť sekciu ${s}`,
    show: "Zobraziť",
    hide: "Skryť",
    saveDefault: "Uložiť aktuálnu viditeľnosť a poradie stĺpcov ako predvolené",
    saved: "Uložené",
    saveColumns: "Uložiť nastavenie stĺpcov",
    persistenceHint: "Poradie aj viditeľnosť sa ukladajú ako predvolené zobrazenie.",
    savedViews: "Uložené pohľady",
    noSavedViews: "Zatiaľ nemáte uložený žiadny pohľad.",
    applyView: "Použiť pohľad",
    overwrite: "Prepísať",
    overwriteTitle: "Prepísať aktuálnym nastavením",
    deleteView: "Odstrániť pohľad",
    viewName: "Názov pohľadu",
    saveView: "Uložiť aktuálne zobrazenie",
    save: "Uložiť",
    accountFormRequired: "Aspoň jedna forma účtu musí zostať zobrazená",
    compactAccountHeading: (l) => `${l} – skrátené kvôli šírke`,
  },
  journalEditor: {
    row: "R.",
    debitAccount: "MD účet",
    creditAccount: "DAL účet",
    counterAccount: "Protiúčet",
    amount: "Suma",
    homeAmount: "Suma v {symbol}",
    foreignAmount: "Suma v {symbol}",
    text: "Text",
    quantity: "Množstvo",
    unit: "MJ",
    unitPrice: "Cena za MJ",
    dimension: "Zákazka",
    vs: "VS",
    partner: "Partner",
    debitDimension: "MD zákazka",
    creditDimension: "DAL zákazka",
    debitVs: "MD VS",
    creditVs: "DAL VS",
    debitPartner: "MD partner",
    creditPartner: "DAL partner",
    nonTax: "Nedaňový",
    nonTaxOn: "Nedaňový",
    nonTaxOff: "Daňový – kliknite pre nedaňový",
    rounding: "Zaokrúhlenie",
    fxRounding: "Kurzové zaokrúhlenie",
    fxRoundingPreview: "Kurzové zaokrúhlenie – dopočíta sa pri uložení",
    fxRoundingHint: "Rozdiel medzi prepočtom celého dokladu a riadkov – vytvára databáza",
    detail: "Detail riadku",
    showDetail: "Zobraziť detail riadku (Alt+↓)",
    hideDetail: "Skryť detail riadku (Alt+↓)",
    sideDebit: "MD",
    sideCredit: "DAL",
    actions: "Akcie",
    addLine: "Pridať riadok",
    duplicateLine: "Duplikovať riadok",
    removeLine: "Odobrať riadok",
    undo: "Späť",
    removed: "Riadok bol odobraný",
    total: "Celkom",
    remaining: "Zostáva rozpísať",
    balanced: "Rozpísané",
    roundingExists: "Zaokrúhlenie už na doklade je",
    errors: "Počet chýb",
    empty: "Zatiaľ tu nie sú žiadne riadky",
    debitRequired: "Vyberte účet MD",
    creditRequired: "Vyberte účet DAL",
    amountRequired: "Suma musí byť nenulová",
    missingVs: "Chýba VS na strane {side}",
    missingDimension: "Chýba zákazka na strane {side}",
    search: "Hľadať v riadkoch…",
    searchResult: "Zobrazené {shown} z {total} riadkov",
    clearSearch: "Zrušiť hľadanie",
    quantityPriceHint: "Množstvo × cena za MJ",
    vatCode: "Kód DPH",
    vatRate: "Sadzba",
    vatAmount: "DPH",
    grossAmount: "Celkom s DPH",
    vatMode: "Zadanie sumy",
    vatModeNet: "Bez DPH",
    vatModeGross: "S DPH",
    vatManual: "Daň zadaná ručne",
    resetVat: "Vrátiť vypočítanú daň",
    vatDeduction: "Nárok na odpočet",
    deductionFull: "Plný",
    deductionNone: "Bez nároku",
    deductionPartial: "Pomerný",
    deductionShare: "Pomer %",
    pdpSubject: "Predmet plnenia PDP",
    vatBaseHome: "Základ pre DPH ({symbol})",
    vatHome: "DPH ({symbol})",
    vatCodeRequired: "Vyberte kód DPH",
    vatDeviation: "Ručná daň sa líši od vypočítanej o {amount}",
    pdpRequired: "Vyberte predmet plnenia PDP",
    deductionShareRange: "Pomerný nárok musí byť 1–99 %",
    vatMissingAccounts: "Chýbajú účty kódu {code} – daň sa nezaúčtuje",
    rate: "Kurz",
    moveRow: "Presunúť riadok",
    nonTaxShort: "ND",
  },
  journalRecap: {
    debitShort: "MD",
    creditShort: "DAL",
    debitAccount: "MD účet",
    creditAccount: "DAL účet",
  },
  documentForm: {
    changeAccount: "Zmeniť účet",
    currencyDisabled: "Menu nie je možné zmeniť",
    mainAccountSelect: "Hlavný účet",
    supplierNumber: "Číslo dokladu dodávateľa",
    supplierTaxDocumentNumber: "Číslo daňového dokladu",
    documentNumberTooLongForVs: "Číslo má viac ako 10 číslic – VS doplňte ručne",
    bankAccountInvalid: "Číslo účtu nie je platné.",
    bankCodeInvalid: "Kód banky nie je platný.",
    otherBankAccount: "Iný účet",
  },
  export: {
    parametersSheet: "Parametre exportu",
    parameter: "Parameter",
    value: "Hodnota",
    reportName: "Názov zostavy",
    company: "Firma",
    period: "Obdobie",
    exportedAt: "Exportované",
    user: "Používateľ",
    activeFilters: "Aktívne filtre",
    pageFooter: "Strana &P z &N",
    fallbackColumn: (i) => `Stĺpec ${i}`,
    printPdf: "Tlač (PDF)…",
  },
  print: {
    book: "Kniha",
    allBooks: "Všetky knihy",
    period: "Obdobie",
    search: "Hľadanie",
    filter: "Filter",
    asOf: "Stav k dátumu",
    total: "Celkom",
    portrait: "Na výšku",
    landscape: "Na šírku",
    orientation: "Orientácia strany",
    largeTitle: "Tlač veľkého objemu údajov",
    largeDescription: (r, p) =>
      `Zostava má ${r} riadkov, odhadom ${p} strán. Príprava PDF môže chvíľu trvať. Pokračovať?`,
    print: "Vytlačiť",
    printTitle: "Tlač",
    downloadPdf: "Stiahnuť PDF",
    preview: "Náhľad",
    preparing: "Pripravujem náhľad…",
    printedBy: "Vytlačil:",
    page: (p, n) => `Strana ${p} z ${n}`,
  },
};
