/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsPrintRouteImport } from './routes/components.print'
import { Route as ComponentsNavigationRouteImport } from './routes/components.navigation'
import { Route as ComponentsGridRouteImport } from './routes/components.grid'
import { Route as ComponentsFormsRouteImport } from './routes/components.forms'
import { Route as ComponentsFeedbackRouteImport } from './routes/components.feedback'
import { Route as ComponentsExcelExportRouteImport } from './routes/components.excel-export'
import { Route as ComponentsAccountingFormsRouteImport } from './routes/components.accounting-forms'
import { Route as Char91__mockupChar93PreviewSplatRouteImport } from './routes/[__mockup].preview.$'
import { Route as Char91__componentChar93PreviewSplatRouteImport } from './routes/[__component].preview.$'

const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsPrintRoute = ComponentsPrintRouteImport.update({
  id: '/components/print',
  path: '/components/print',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsNavigationRoute = ComponentsNavigationRouteImport.update({
  id: '/components/navigation',
  path: '/components/navigation',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsGridRoute = ComponentsGridRouteImport.update({
  id: '/components/grid',
  path: '/components/grid',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsFormsRoute = ComponentsFormsRouteImport.update({
  id: '/components/forms',
  path: '/components/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsFeedbackRoute = ComponentsFeedbackRouteImport.update({
  id: '/components/feedback',
  path: '/components/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsExcelExportRoute = ComponentsExcelExportRouteImport.update({
  id: '/components/excel-export',
  path: '/components/excel-export',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsAccountingFormsRoute =
  ComponentsAccountingFormsRouteImport.update({
    id: '/components/accounting-forms',
    path: '/components/accounting-forms',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91__mockupChar93PreviewSplatRoute =
  Char91__mockupChar93PreviewSplatRouteImport.update({
    id: '/__mockup/preview/$',
    path: '/__mockup/preview/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91__componentChar93PreviewSplatRoute =
  Char91__componentChar93PreviewSplatRouteImport.update({
    id: '/__component/preview/$',
    path: '/__component/preview/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guidelines': typeof GuidelinesRoute
  '/components/accounting-forms': typeof ComponentsAccountingFormsRoute
  '/components/excel-export': typeof ComponentsExcelExportRoute
  '/components/feedback': typeof ComponentsFeedbackRoute
  '/components/forms': typeof ComponentsFormsRoute
  '/components/grid': typeof ComponentsGridRoute
  '/components/navigation': typeof ComponentsNavigationRoute
  '/components/print': typeof ComponentsPrintRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guidelines': typeof GuidelinesRoute
  '/components/accounting-forms': typeof ComponentsAccountingFormsRoute
  '/components/excel-export': typeof ComponentsExcelExportRoute
  '/components/feedback': typeof ComponentsFeedbackRoute
  '/components/forms': typeof ComponentsFormsRoute
  '/components/grid': typeof ComponentsGridRoute
  '/components/navigation': typeof ComponentsNavigationRoute
  '/components/print': typeof ComponentsPrintRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guidelines': typeof GuidelinesRoute
  '/components/accounting-forms': typeof ComponentsAccountingFormsRoute
  '/components/excel-export': typeof ComponentsExcelExportRoute
  '/components/feedback': typeof ComponentsFeedbackRoute
  '/components/forms': typeof ComponentsFormsRoute
  '/components/grid': typeof ComponentsGridRoute
  '/components/navigation': typeof ComponentsNavigationRoute
  '/components/print': typeof ComponentsPrintRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guidelines'
    | '/components/accounting-forms'
    | '/components/excel-export'
    | '/components/feedback'
    | '/components/forms'
    | '/components/grid'
    | '/components/navigation'
    | '/components/print'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/guidelines'
    | '/components/accounting-forms'
    | '/components/excel-export'
    | '/components/feedback'
    | '/components/forms'
    | '/components/grid'
    | '/components/navigation'
    | '/components/print'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
  id:
    | '__root__'
    | '/'
    | '/guidelines'
    | '/components/accounting-forms'
    | '/components/excel-export'
    | '/components/feedback'
    | '/components/forms'
    | '/components/grid'
    | '/components/navigation'
    | '/components/print'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuidelinesRoute: typeof GuidelinesRoute
  ComponentsAccountingFormsRoute: typeof ComponentsAccountingFormsRoute
  ComponentsExcelExportRoute: typeof ComponentsExcelExportRoute
  ComponentsFeedbackRoute: typeof ComponentsFeedbackRoute
  ComponentsFormsRoute: typeof ComponentsFormsRoute
  ComponentsGridRoute: typeof ComponentsGridRoute
  ComponentsNavigationRoute: typeof ComponentsNavigationRoute
  ComponentsPrintRoute: typeof ComponentsPrintRoute
  Char91__componentChar93PreviewSplatRoute: typeof Char91__componentChar93PreviewSplatRoute
  Char91__mockupChar93PreviewSplatRoute: typeof Char91__mockupChar93PreviewSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/print': {
      id: '/components/print'
      path: '/components/print'
      fullPath: '/components/print'
      preLoaderRoute: typeof ComponentsPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/navigation': {
      id: '/components/navigation'
      path: '/components/navigation'
      fullPath: '/components/navigation'
      preLoaderRoute: typeof ComponentsNavigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/grid': {
      id: '/components/grid'
      path: '/components/grid'
      fullPath: '/components/grid'
      preLoaderRoute: typeof ComponentsGridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/forms': {
      id: '/components/forms'
      path: '/components/forms'
      fullPath: '/components/forms'
      preLoaderRoute: typeof ComponentsFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/feedback': {
      id: '/components/feedback'
      path: '/components/feedback'
      fullPath: '/components/feedback'
      preLoaderRoute: typeof ComponentsFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/excel-export': {
      id: '/components/excel-export'
      path: '/components/excel-export'
      fullPath: '/components/excel-export'
      preLoaderRoute: typeof ComponentsExcelExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/accounting-forms': {
      id: '/components/accounting-forms'
      path: '/components/accounting-forms'
      fullPath: '/components/accounting-forms'
      preLoaderRoute: typeof ComponentsAccountingFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__mockup/preview/$': {
      id: '/__mockup/preview/$'
      path: '/__mockup/preview/$'
      fullPath: '/__mockup/preview/$'
      preLoaderRoute: typeof Char91__mockupChar93PreviewSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__component/preview/$': {
      id: '/__component/preview/$'
      path: '/__component/preview/$'
      fullPath: '/__component/preview/$'
      preLoaderRoute: typeof Char91__componentChar93PreviewSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuidelinesRoute: GuidelinesRoute,
  ComponentsAccountingFormsRoute: ComponentsAccountingFormsRoute,
  ComponentsExcelExportRoute: ComponentsExcelExportRoute,
  ComponentsFeedbackRoute: ComponentsFeedbackRoute,
  ComponentsFormsRoute: ComponentsFormsRoute,
  ComponentsGridRoute: ComponentsGridRoute,
  ComponentsNavigationRoute: ComponentsNavigationRoute,
  ComponentsPrintRoute: ComponentsPrintRoute,
  Char91__componentChar93PreviewSplatRoute:
    Char91__componentChar93PreviewSplatRoute,
  Char91__mockupChar93PreviewSplatRoute: Char91__mockupChar93PreviewSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
